### ISSUE TITLE
Add support for async functions returning opaque Rust types

### ISSUE THREAD

**Issue by josephg** [chinedufn/swift-bridge#120]
I've got a quite complicated type I'm sharing via the swift bridge interface. I'm using an opaque type, but I want to use the async function bridge and it looks like thats not supported:

```
   Compiling dt-swift v0.1.0 (/Users/seph/src/diamond-types/crates/dt-swift)
error: failed to run custom build command for `dt-swift v0.1.0 (/Users/seph/src/diamond-types/crates/dt-swift)`

Caused by:
  process didn't exit successfully: `/Users/seph/src/diamond-types/target/release/build/dt-swift-82fb4d8c023013ad/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=src/lib.rs

  --- stderr
  thread 'main' panicked at 'not implemented', /Users/seph/.cargo/registry/src/github.com-1ecc6299db9ec823/swift-bridge-ir-0.1.41/src/bridged_type/bridged_opaque_type.rs:71:21
```

The code for [async functions in opaque types is unimplemented](https://github.com/chinedufn/swift-bridge/blob/e2da694fbbd1a0708863591cd36da913d5298e51/crates/swift-bridge-ir/src/bridged_type/bridged_opaque_type.rs#L70-L72):

```rust
                TypePosition::SwiftCallsRustAsyncOnCompleteReturnTy => {
                    unimplemented!()
                }
```

- What is needed to add support here?
- Are there any workarounds? Can I have a bridged struct with an opaque reference or something?

**Comment by chinedufn** [comment]
Yup, having async functions return opaque Rust types is not yet supported. 

> What is needed to add support here?

We'd first want to add an integration test, similar to the one for returning returning a transparent struct from an async function.

https://github.com/chinedufn/swift-bridge/blob/dc1119e1ee333e1412f81f726987637b8f620a58/crates/swift-integration-tests/src/async_function.rs#L9

https://github.com/chinedufn/swift-bridge/blob/dc1119e1ee333e1412f81f726987637b8f620a58/crates/swift-integration-tests/src/async_function.rs#L32-L34

https://github.com/chinedufn/swift-bridge/blob/dc1119e1ee333e1412f81f726987637b8f620a58/SwiftRustIntegrationTestRunner/SwiftRustIntegrationTestRunnerTests/AsyncTests.swift#L44-L46

---

Next we'd add a codegen test for returning an opaque Rust type from an async function. Similar to:

https://github.com/chinedufn/swift-bridge/blob/dc1119e1ee333e1412f81f726987637b8f620a58/crates/swift-bridge-ir/src/codegen/codegen_tests/async_function_codegen_tests.rs#L357-L424

---

Then we'd get the codegen tests passing.

In this case this would boil down to tweaking code in `bridged_type.rs` until the test passed.

https://github.com/chinedufn/swift-bridge/blob/c1fd7177b5d3a8918e34b6bc96ae29437cfc1487/crates/swift-bridge-ir/src/bridged_type.rs#L45

---

After that we would verify that the integration test was passing by running `./test-integration.sh`.

---

I just added some basic documentation on adding support for types / function signatures:

https://chinedufn.github.io/swift-bridge/contributing/adding-support-for-a-signature/index.html

> Are there any workarounds? Can I have a bridged struct with an opaque reference or something?

That _should_ work, but we haven't yet added explicit tests for `struct SomeTransparentStruct { field: SomeOpaqueRustType }` so I can't say with certainty. So far we only explicitly support primitive fields.

https://github.com/chinedufn/swift-bridge/blob/b74432885120fbc6025349d8694505ec3b950918/crates/swift-integration-tests/src/shared_types/shared_struct.rs#L14

... but... it _should_ work since the code for bridging struct primitive struct fields hits the same code paths as bridging any other type..

**Comment by chinedufn** [comment]
Related implementation for `async fn some_function() -> Result<OpaqueRust, OpaqueRust> 

#158 

And the corresponding issue

#157

**Comment by chinedufn** [comment]
This was implemented in https://github.com/chinedufn/swift-bridge/commit/c4a11f4e3fa7e9c0e1652f4e21e9b3d94c6c837b
