### ISSUE TITLE
Add an option to run Swift build functions silently (without any output to stdout)

### ISSUE THREAD

**Issue by antoniusnaumann** [chinedufn/swift-bridge#142]
For usage in dedicated build / bundling tools, it would be handy to configure or use the swift_bridge_build functions silently, without producing output to stdout (being aware of the drawbacks, this includes cargo-commands (cargo-rerun-if, etc.)).

A few possible solutions:
- crate feature flag (e.g. silent) that is disabled by default (+ does not bother users who do not need this, - makes the setting global, so no fine-grained control possible)
- introduce additional parameter to functions (+ fine-grained control, - bothers everybody, even if this is not needed / not advisable for people who use swift_bridge_build in a build.rs file)
- introduce a silent function for every function (+ fine-grained control, - refactoring / maintainance and probably migration overhead, - invoking the wrong version of a function accidentally is possible)
- provide no solution for this. If using swift_bridge_build in separate tools instead of invoking it in build.rs is strongly discouraged, this is also an option to consider.

Context: I am building [cargo-swift](https://github.com/antoniusnaumann/cargo-swift) that is intended to be an opinionated, user-friendly convenience layer above swift_bridge, mainly aiding in setting up boilerplate and building a Swift package from your codebase without requiring any extra build configuration (steps that would be required in build.rs (e.g. generating bridging header) as well as scripts such as lipo. It therefore pursues other goals than the swift-bridge-cli which enables more fine-grained control but requires setting up a custom project build config and external tools (e.g. lipo) to be invoked manually)

I am willing to work on this feature after discussing how it should be integrated. I am in favor of providing this as a crate feature that is disabled by default.

**Comment by chinedufn** [comment]
I'm only aware of the `cargo:rerun-if-changed` lines being written to stdout. Is there anything else that you have in mind?

I think we want `swift-bridge-build` to be silent when there aren't any errors.

We can actually delete the `cargo:rerun-if-changed` that you're running into since it isn't needed.
(The files that we're printing out don't even exist anymore.)

So, we can delete this:

https://github.com/chinedufn/swift-bridge/blob/54b9c09337701dd7580010d1d5ef6527b855ee98/crates/swift-bridge-build/src/generate_core.rs#L46-L54

Does that solve your problem?

---

> If using swift_bridge_build in separate tools instead of invoking it in build.rs is strongly discouraged, this is also an option to consider.

Thanks for listing out all of the potential options that you had in mind. I'd just like to say that using `swift-bridge-build` from other tools is **very** much encouraged!

Please feel free to open issues whenever you run into something that `cargo swift` needs.

**Comment by antoniusnaumann** [comment]
Perfect. I'll add a PR for this.

The culprit for the remaining stdout is actually xcodebuild (which prints out "xcframework successfully written out to: ..."). Since xcodebuild has a --quiet option, this can be silenced. But as this output can be actually useful, always silencing is probably not appropriate. I'll include a suggested implementation in my PR.

**Comment by chinedufn** [comment]
> But as this output can be actually useful

I'm sure that the `stderr` output is useful if you're trying to figure out what went wrong during a build, but when is the `stdout` output useful?

---

We should be able to capture the `stdout` from the `xcodebuild` command by using [Command.output](https://doc.rust-lang.org/std/process/struct.Command.html#method.output) instead of `Command.spawn`.

https://github.com/chinedufn/swift-bridge/blob/03de7ea4fb646de1b71358a717488ddac5d67e97/crates/swift-bridge-build/src/package.rs#L230-L233

**Comment by chinedufn** [comment]
Re-opening since I think we should capture the `xcodebuild` output and, at least for now, do nothing with the `stdout`.

This should make the command completely silent on success, and panic with with errors.

Then at some point in the future we'd want to refactor the create package function to return a Result.

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/swift-bridge/pull/144
