### ISSUE TITLE
Support Computed-Properties for Swift

### ISSUE THREAD

**Issue by NiwakaDev** [chinedufn/swift-bridge#154]
`swift-bridge` supports a getter like this right now: 

```rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type SomeType;

        #[swift_bridge(get(my_u8))]
        fn my_u8(&self) -> u8;
    }
}
```

```Swift
//Swift
let someType = SomeType() 
print(someType.my_u8())
```

In Swift, a gettter and a setter can get a little simpler using `Computed Properties`. 
`Computed Properties` provides a getter and an optional setter instead of storing a value.

Here's an example of using `Computed Properties`. 

```Swift
extension SomeTypeRef {
    public var my_u8: UInt8 {
       //If we don't implement a setter, my_u8 will be a read-only variable.
        get{
            return  __swift_bridge__$SomeType$my_u8(ptr)
        }
    }
}

let someType = SomeType()
print(someType.my_u8)
```

## Resource

<a href="https://docs.swift.org/swift-book/LanguageGuide/Properties.html">Properties</a>

**Comment by chinedufn** [comment]
The `#[swift_bridge(get)]` attribute allows you to get the value by using a field instead of calling a method.

https://github.com/chinedufn/swift-bridge/blob/b068c8f5de3119316b3a8cf65686eb6721ec52b3/book/src/bridge-module/functions/README.md?plain=1#L130-L157

That being said, if the name makes it sound like it's used to create Swift getters then we can consider renaming it.

---

We could figure out a good way to support computed properties if they useful, but I'm not yet seeing the use case?

When would generating a computed property instead of a Swift class method be useful?

It seems like computed properties are useful when they're being computed based on other properties.

```swift
class Point {
    var x: Int
    var y: Int
    var xPlusY: UInt {
        get {  
            return x + y 
        }
}
```

Or is there another use case that you have in mind? (I quickly canned the `Properties` link that you shared, but haven't read it through it more carefully yet).

**Comment by NiwakaDev** [comment]
>We could figure out a good way to support computed properties if they useful, but I'm not yet seeing the use case?

Actually, they might not useful. It’s just a matter of preference.

**Comment by chinedufn** [comment]
In that case I say we hold off on this until someone comes with a compelling use case.

There's other stuff in that Properties chapter in the Swift language guide that we might want to consider though.

For example, supporting things like property wrappers could potentially be useful. 
I've only ever used the ones that are common in SwiftUI (such as `@Binding`) and I've never written my own, so I'm not sure how people tend to use them and how useful they are.

Anyways, I'll close out this issue about computed properties for now. If someone comes with a compelling use case we can reconsider it.

Thanks for looking into this!
