### ISSUE TITLE
Support `Result<T, E>` where `E` is enum type.

### ISSUE THREAD

**Issue by NiwakaDev** [chinedufn/swift-bridge#159]
related to #152?

```rust
#[swift_bridge::bridge]
mod ffi {
    enum NetworkError {
        Authentication(String),
        Unknown,
        JsonParse,
    }

    extern "Rust" {
        type Data;
        async fn fetch_from_server() -> Result<Data, NetworkError>;
    }
}
```

**Comment by NiwakaDev** [comment]
As far as I understand, I guess `swift-bridge` doesn't work right now.

**Comment by chinedufn** [comment]
By the way, enums with data are not yet supported. Just created a new issue for that https://github.com/chinedufn/swift-bridge/issues/160

---

Right now, the `T` and `E` in a `Result<T, E>` only work for types that are passed between Swift and Rust as pointers.

We support this using https://github.com/chinedufn/swift-bridge/blob/420ed791c0cef08f7cfff7f4024ee39cd13d31c2/src/std_bridge/result.rs#L1-L7 and https://github.com/chinedufn/swift-bridge/blob/420ed791c0cef08f7cfff7f4024ee39cd13d31c2/crates/swift-bridge-build/src/generate_core/result_support.rs#L38-L40

Primitives, structs and enums aren't passed over FFI as pointers.

Primitives get passed as `C` primitives: 

https://github.com/chinedufn/swift-bridge/blob/07a15d78782dc371a7d24301ac9625124e42f8d8/crates/swift-bridge-ir/src/codegen/generate_c_header.rs#L453-L464

Structs and enums get passed as `C` structs that we generate at compile time:

https://github.com/chinedufn/swift-bridge/blob/c1fd7177b5d3a8918e34b6bc96ae29437cfc1487/crates/swift-bridge-ir/src/codegen/codegen_tests/transparent_struct_codegen_tests.rs#L78-L81

https://github.com/chinedufn/swift-bridge/blob/819e39160ec5b38dce2e60e2d39d078617ad158d/crates/swift-bridge-ir/src/codegen/codegen_tests/transparent_enum_codegen_tests.rs#L101-L105

---

So, to support `Result<T, E>` where either `T` or `E` isn't a pointer we need to generate an FFI representation on the fly like we currently do for transparent `struct`s and `enum`s.

---

Does that make sense?

**Comment by NiwakaDev** [comment]
>By the way, enums with data are not yet supported. Just created a new issue for that https://github.com/chinedufn/swift-bridge/issues/160

According to [The swift-bridge Book](https://chinedufn.github.io/swift-bridge/bridge-module/transparent-types/enums/index.html#transparent-enums), `swift-bridge` seems to support this. Is this unrelated?

**Comment by NiwakaDev** [comment]
>Does that make sense? 

To be honest, Now I understand only half of what you wrote. I'll read it this weekends, and think through it.

**Comment by NiwakaDev** [comment]
>When using ResultPtrAndPtr T or E gets passed between languages using in the ok_or_err: *mut std::ffi::c_void pointer.
Primitives, structs and enums aren't passed over FFI as pointers.

I see. I finally understand now!!

**Comment by NiwakaDev** [comment]
This issue might be related to:

https://github.com/chinedufn/swift-bridge/blob/8c7d1a3bb8c74a16e9417fbecb987896b52e7980/src/std_bridge/result.rs#L9-L33

**Comment by chinedufn** [comment]
Sort of.

We can't manually define `Result<Enum, Enum>` FFI representations ahead of time since we don't know your enum's FFI representation until we parse the bridge module.

So, we need to generate it on the fly.

So, a bridge module like:

```rust
#{swift_bridge::bridge}
mod module_name {
    enum MyEnum1 {
        VariantA
    }
    enum MyEnum2 {
        VariantB
    }

    extern "Rust" {
        fn x() -> Result<MyEnum1, MyEnum2>;
        fn y(arg: Result<MyEnum1, MyEnum2>);
    } 
}
```

Might generate something like:

```
// Generated Rust (rough sketch)

#[repr(C)]
struct __swift_bridge__module_name_Result_MyEnum1_MyEnum2 {
    is_ok: bool,
    data: __swift_bridge__module_name_Union_MyEnum1_MyEnum2
}
struct __swift_bridge__module_name_Union_MyEnum1_MyEnum2 {
    first: MyEnum1,
    second: MyEnum2
}
```

---

Does that make sense?

**Comment by NiwakaDev** [comment]
Thank you for your quick reply. Sorry... I just wanted to confirm the following: 
>When using ResultPtrAndPtr T or E gets passed between languages using in the ok_or_err: *mut std::ffi::c_void pointer.
Primitives, structs and enums aren't passed over FFI as pointers.

**Comment by chinedufn** [comment]
No problem! But I'm not sure what you're asking?

**Comment by NiwakaDev** [comment]
I apologize for any mistakes in my English.

>But I'm not sure what you're asking?

I wanted to say to you that " Regardless of whether it's manual or automatic, does the code we want to generate resemble the following? "

**Comment by chinedufn** [comment]
For types where the `T` and `E` are passed over FFI as pointers, such as `Result<OpaqueRust, OpaqueRust>` we do not need to generate a custom result representation.

For types that are not passed over FFI as pointers, such as `Result<Enum, Enum>`, we need to generate a custom result representation.

So, we can add a method too the `trait BridgeableType.fn is_passed_via_pointer(&self) -> bool`.

Then during parsing if we see a `Result<T, E>` we run `is_passed_via_pointer()` on `T` and `E`.

If both are true then we don't need to generate a custom result since we can use `ResultPtrAndPtr`. For example, `Result<OpaqueRust, OpaqueRust>` would not need a custom representation since `OpaqueRust.is_passed_via_pointer() == true`.

If both either `T.is_passed_via_pointer()` or `E.is_passed_via_pointer()` returns false then we need to generate a custom result.

---

Does that make sense, or no?

---

A good starting point might be to write the integration and codegen tests. I'd be happy to give feedback on those.

---

But yeah, if you have more questions feel free to keep asking here!

**Comment by NiwakaDev** [comment]
>Does that make sense, or no?

Yes!! Thank you!! I'll implement this feature this week or next week! 

>But yeah, if you have more questions feel free to keep asking here!

Thank you! I always appreciate your help!

**Comment by NiwakaDev** [comment]
You think we can `union` to implement this feature.

something like this: 
```rust
#[repr(C)]
struct __swift_bridge__module_name_Result_MyEnum1_MyEnum2 {
    is_ok: bool,
    data: __swift_bridge__module_name_Union_MyEnum1_MyEnum2
}
#[repr(C)]
union __swift_bridge__module_name_Union_MyEnum1_MyEnum2 {
    first: MyEnum1,
    second: MyEnum2
}
```

How about using only a `struct` to represent a custom result something like:
```rust
  #[repr(C)] 
 pub struct ResultMyEnum1AndMyEnum1 { 
      pub is_ok: bool, 
      pub ok: MyEnum1, 
      pub err: MyEnum1 
 } 
```

**Comment by chinedufn** [comment]
The advantage of the union approach is that it uses less memory than having both fields in the struct.

For example, if `T` is 200 bytes and `E` is 500 bytes, then the size of `struct Foo { ok: T, err: E}` is ~700 bytes, whereas the size of `union Bar {ok: T, err: E}` is ~500 bytes.

Why do you ask? What do you have in mind?

**Comment by NiwakaDev** [comment]
This is really what I wanted to ask. So, I asked you about the following:
https://github.com/chinedufn/swift-bridge/blob/8c7d1a3bb8c74a16e9417fbecb987896b52e7980/src/std_bridge/result.rs#L9-L33

 Until yesterday I thought that :
"*I guess we can use only a struct to implement this feature, such as ResultU8AndU8 or ResultU8AndU16*"

However, due to my insufficient English, I have caused you to misunderstand.

But now, I understand the reason why we should avoid using only a struct. 
I deeply apologize for taking so long.

**Comment by chinedufn** [comment]
Ok cool.

Those comments are old and aren't the best approach.

For example, since `Result<u8, u16>` is an incredibly uncommon use case, it might not make sense to have a dedicated FFI representation.
We might instead generate one on the fly like we are doing for transparent enums, or we might have something like `ResultPrimitiveU16 {is_ok: bool, largest_type: [u8; 2]`, which could then handle `Result<T, E>` for any combination of `T` and `E` primitives that are both less than or equal to two bytes by encoding those bytes into 0 or more of the `largest_type` bytes.

That's just a quick example. There are other ways to solve the problem. **For now we don't need to worry about bridging primitive Results since it isn't a common use case. When we want to address it we can explore the design space more thoroughly and pick the best design.**

So, I deleted that `ResultU8AndPtr` comment here https://github.com/chinedufn/swift-bridge/commit/e9e312c470f924c93252aba850ec5fd3273714ae

> I deeply apologize for taking so long.

I've actually been telling my real-life friends that someone named `NiwakaDev` showed up and started making AWESOME contributions. It's so exciting. So, no need to apologize. I'm absolute loving your work!

Thanks!

**Comment by NiwakaDev** [comment]
I'll implement returning `Result<transparent enum, transparent enum>` from `async` functions next week.

**Comment by chinedufn** [comment]
Sweet!

**Comment by NiwakaDev** [comment]
I'll implement `Result<(), TransparentEnum>` this week.

**Comment by chinedufn** [comment]
Done!
