### ISSUE TITLE
Why Rust's struct with public no fields has a private field?

### ISSUE THREAD

**Issue by NiwakaDev** [chinedufn/swift-bridge#165]
On the Rust side, `SomeStruct` has no fields.

https://github.com/chinedufn/swift-bridge/blob/3238914429980d105d8d93de143d391a6f74ffa6/crates/swift-bridge-ir/src/codegen/codegen_tests/transparent_struct_codegen_tests.rs#L12-L16

However, `__swift_bridge__SomeStruct` has one field, which is used on the Swift Side.

https://github.com/chinedufn/swift-bridge/blob/3238914429980d105d8d93de143d391a6f74ffa6/crates/swift-bridge-ir/src/codegen/codegen_tests/transparent_struct_codegen_tests.rs#L24-L28

**Comment by NiwakaDev** [comment]
By the way, I guess `SomeStruct` with no fields can be generated like this: 

```rust
 #[repr(C)] 
 #[doc(hidden)] 
 pub struct SomeStruct { 
 
} 
```

So, `SomeStruct` could be directly used on the Swift Side.

**Comment by chinedufn** [comment]
Ah, good question. I should've left a comment.

---

It's written like that because I wanted a type that was FFI safe.

Zero-sized types are not FFI safe.

```rust
#[repr(C)]
struct Zst;

unsafe extern "C" fn x() -> Zst {
    unimplemented!()
}

fn main() {}
```

```
warning: `extern` fn uses type `Zst`, which is not FFI-safe
 --> src/main.rs:4:29
  |
4 | unsafe extern "C" fn x() -> Zst {
  |                             ^^^ not FFI-safe
  |
  = help: consider adding a member to this struct
  = note: this struct has no fields
```

---

I'll close this in favor of https://github.com/chinedufn/swift-bridge/issues/14 , which seeks to "solve" this by not even having an FFI representation for ZSTs at all.
