### ISSUE TITLE
Support for returning Result<(), OpaqueType>

### ISSUE THREAD

**Issue by jfaust** [chinedufn/swift-bridge#177]
Currently if I try to use an empty tuple in a Result I get:

```
error[E0605]: non-primitive cast: `()` as `*mut c_void`
  --> ios/rust/src/lib.rs:81:1
   |
81 | #[swift_bridge::bridge]
   | ^^^^^^^^^^^^^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
   |
```

I'm working around it by using an empty `None` struct for now, but it'd be nice to convert this to a Swift function returning void.

**Comment by chinedufn** [comment]
Thanks for the report.

I'd like to change this issue to be about the particular kind of `E` that you are using in your `Result<(), E>`. (i.e. opaque type, shared struct, shared enum, primitive, etc..).

The reason is that since `()` does not need an FFI representation (since the type always has the same value), we can add special case optimizations for some kinds of `Result<(), E>`.

For example, opaque types such as `type SomeType` get bridged as `*mut SomeType`.

This `*mut SomeType` pointer is never null, so `Result<(), SomeType>` can be bridged with a single pointer`*mut SomeType`, where `()` gets encoded as a null pointer.

I'd like to implement things that people are running into in real code, vs. tracking/implementing support for all `Result<(), ...>` in one issue.

Just giving you some context.

---

Anyways, what kind of `E` are you using? If it's an opaque type mind changing the issue name to `Support for Result<(), OpaqueType>`.

From there I can write up a thorough `good first issue` guide so that anyone that comes across this issue and is interested can quickly add support.

**Comment by jfaust** [comment]
Well, I've been updating my bindings to use the new `Result` support. At the moment I'm using `Result<(), OpaqueType>` - however, I'd love to use an enum when that becomes possible (https://github.com/chinedufn/swift-bridge/issues/159).

I'll update this issue to be for `Result<(), OpaqueType>`. This is actually something I may try to tackle & submit a PR, as using an empty struct results in a lot of `let _ = ...` on the Swift side.

**Comment by chinedufn** [comment]
Returning `Result<(), OpaqueType>` was implemented in https://github.com/chinedufn/swift-bridge/pull/180

I'll close this out. We can handle `Result<(), OpaqueType>` separately.

Thanks for opening and solving this!

**Comment by qui-jason** [comment]
Awesome, we needed this today! Thanks @jfaust and @chinedufn!
