### ISSUE TITLE
Building for Release

### ISSUE THREAD

**Issue by lockieluke** [chinedufn/swift-bridge#249]
I tried building with `--release` and it came back with `Symbol not found: XXX` when I try to run my app with the release library linked to it, is there any way to properly build a release library?

**Comment by chinedufn** [comment]
It should be possible to build and link to a release library today.

Can you share a reproducible example project?

**Comment by lockieluke** [comment]
I sent you the repo via email as it is a closed source project at the moment

**Comment by bes** [comment]
Could it be the same as this issue https://github.com/chinedufn/swift-bridge/issues/166 ?

**Comment by chinedufn** [comment]
> I sent you the repo via email as it is a closed source project at the moment

It ended up in my spam folder. But, in the future, would prefer a minimal reproduction that I can look at before downloading so that I don't have to download code before reading it.

---

> Could it be the same as this issue https://github.com/chinedufn/swift-bridge/issues/166 ?

Ahhh nice!

@lockieluke here's how to solve it. Should be pretty easy if you want to -> https://github.com/chinedufn/swift-bridge/issues/166#issuecomment-1428821701

**Comment by chinedufn** [comment]
Closing in favor of https://github.com/chinedufn/swift-bridge/issues/166
